[profile.default]
src = 'src'
out = 'out'
libs = ["node_modules", "lib"]
remappings = ['@uniswap/=node_modules/@uniswap/']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config